PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_YFI_V007_CONST_H CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD YFI_V007_CONST_H-APLICA .
    FIELD YFI_V007_CONST_H-CGROUP .
    FIELD YFI_V007_CONST_H-GRPTX .
    FIELD YFI_V007_CONST_H-ACTIV .
    FIELD YFI_V007_CONST_H-ERNAM .
    FIELD YFI_V007_CONST_H-ERDAT .
    FIELD YFI_V007_CONST_H-ERZET .
    FIELD YFI_V007_CONST_H-AENAM .
    FIELD YFI_V007_CONST_H-AEDAT .
    FIELD YFI_V007_CONST_H-AEZET .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD YFI_V007_CONST_H-APLICA .
    FIELD YFI_V007_CONST_H-CGROUP .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
