*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: YFI_V006_DONACIO................................*
FORM GET_DATA_YFI_V006_DONACIO.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM YFI_T006_DONACIO WHERE
(VIM_WHERETAB) .
    CLEAR YFI_V006_DONACIO .
YFI_V006_DONACIO-MANDT =
YFI_T006_DONACIO-MANDT .
YFI_V006_DONACIO-ZNEWKO_DON =
YFI_T006_DONACIO-ZNEWKO_DON .
YFI_V006_DONACIO-TXT_DON =
YFI_T006_DONACIO-TXT_DON .
YFI_V006_DONACIO-UNAME =
YFI_T006_DONACIO-UNAME .
YFI_V006_DONACIO-AEDTM =
YFI_T006_DONACIO-AEDTM .
YFI_V006_DONACIO-UZEIT =
YFI_T006_DONACIO-UZEIT .
<VIM_TOTAL_STRUC> = YFI_V006_DONACIO.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_YFI_V006_DONACIO .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO YFI_V006_DONACIO.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_YFI_V006_DONACIO-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM YFI_T006_DONACIO WHERE
  ZNEWKO_DON = YFI_V006_DONACIO-ZNEWKO_DON .
    IF SY-SUBRC = 0.
    DELETE YFI_T006_DONACIO .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM YFI_T006_DONACIO WHERE
  ZNEWKO_DON = YFI_V006_DONACIO-ZNEWKO_DON .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR YFI_T006_DONACIO.
    ENDIF.
YFI_T006_DONACIO-MANDT =
YFI_V006_DONACIO-MANDT .
YFI_T006_DONACIO-ZNEWKO_DON =
YFI_V006_DONACIO-ZNEWKO_DON .
YFI_T006_DONACIO-TXT_DON =
YFI_V006_DONACIO-TXT_DON .
YFI_T006_DONACIO-UNAME =
YFI_V006_DONACIO-UNAME .
YFI_T006_DONACIO-AEDTM =
YFI_V006_DONACIO-AEDTM .
YFI_T006_DONACIO-UZEIT =
YFI_V006_DONACIO-UZEIT .
    IF SY-SUBRC = 0.
    UPDATE YFI_T006_DONACIO ##WARN_OK.
    ELSE.
    INSERT YFI_T006_DONACIO .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_YFI_V006_DONACIO-UPD_FLAG,
STATUS_YFI_V006_DONACIO-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_YFI_V006_DONACIO.
  SELECT SINGLE * FROM YFI_T006_DONACIO WHERE
ZNEWKO_DON = YFI_V006_DONACIO-ZNEWKO_DON .
YFI_V006_DONACIO-MANDT =
YFI_T006_DONACIO-MANDT .
YFI_V006_DONACIO-ZNEWKO_DON =
YFI_T006_DONACIO-ZNEWKO_DON .
YFI_V006_DONACIO-TXT_DON =
YFI_T006_DONACIO-TXT_DON .
YFI_V006_DONACIO-UNAME =
YFI_T006_DONACIO-UNAME .
YFI_V006_DONACIO-AEDTM =
YFI_T006_DONACIO-AEDTM .
YFI_V006_DONACIO-UZEIT =
YFI_T006_DONACIO-UZEIT .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_YFI_V006_DONACIO USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE YFI_V006_DONACIO-ZNEWKO_DON TO
YFI_T006_DONACIO-ZNEWKO_DON .
MOVE YFI_V006_DONACIO-MANDT TO
YFI_T006_DONACIO-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'YFI_T006_DONACIO'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN YFI_T006_DONACIO TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'YFI_T006_DONACIO'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
