*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: YFI_V007_CONST_H................................*
FORM GET_DATA_YFI_V007_CONST_H.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM YFI_T007_CONST_H WHERE
(VIM_WHERETAB) .
    CLEAR YFI_V007_CONST_H .
YFI_V007_CONST_H-MANDT =
YFI_T007_CONST_H-MANDT .
YFI_V007_CONST_H-APLICA =
YFI_T007_CONST_H-APLICA .
YFI_V007_CONST_H-CGROUP =
YFI_T007_CONST_H-CGROUP .
YFI_V007_CONST_H-GRPTX =
YFI_T007_CONST_H-GRPTX .
YFI_V007_CONST_H-ACTIV =
YFI_T007_CONST_H-ACTIV .
YFI_V007_CONST_H-ERNAM =
YFI_T007_CONST_H-ERNAM .
YFI_V007_CONST_H-ERDAT =
YFI_T007_CONST_H-ERDAT .
YFI_V007_CONST_H-ERZET =
YFI_T007_CONST_H-ERZET .
YFI_V007_CONST_H-AENAM =
YFI_T007_CONST_H-AENAM .
YFI_V007_CONST_H-AEDAT =
YFI_T007_CONST_H-AEDAT .
YFI_V007_CONST_H-AEZET =
YFI_T007_CONST_H-AEZET .
<VIM_TOTAL_STRUC> = YFI_V007_CONST_H.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_YFI_V007_CONST_H .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO YFI_V007_CONST_H.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_YFI_V007_CONST_H-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM YFI_T007_CONST_H WHERE
  APLICA = YFI_V007_CONST_H-APLICA AND
  CGROUP = YFI_V007_CONST_H-CGROUP .
    IF SY-SUBRC = 0.
    DELETE YFI_T007_CONST_H .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM YFI_T007_CONST_H WHERE
  APLICA = YFI_V007_CONST_H-APLICA AND
  CGROUP = YFI_V007_CONST_H-CGROUP .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR YFI_T007_CONST_H.
    ENDIF.
YFI_T007_CONST_H-MANDT =
YFI_V007_CONST_H-MANDT .
YFI_T007_CONST_H-APLICA =
YFI_V007_CONST_H-APLICA .
YFI_T007_CONST_H-CGROUP =
YFI_V007_CONST_H-CGROUP .
YFI_T007_CONST_H-GRPTX =
YFI_V007_CONST_H-GRPTX .
YFI_T007_CONST_H-ACTIV =
YFI_V007_CONST_H-ACTIV .
YFI_T007_CONST_H-ERNAM =
YFI_V007_CONST_H-ERNAM .
YFI_T007_CONST_H-ERDAT =
YFI_V007_CONST_H-ERDAT .
YFI_T007_CONST_H-ERZET =
YFI_V007_CONST_H-ERZET .
YFI_T007_CONST_H-AENAM =
YFI_V007_CONST_H-AENAM .
YFI_T007_CONST_H-AEDAT =
YFI_V007_CONST_H-AEDAT .
YFI_T007_CONST_H-AEZET =
YFI_V007_CONST_H-AEZET .
    IF SY-SUBRC = 0.
    UPDATE YFI_T007_CONST_H ##WARN_OK.
    ELSE.
    INSERT YFI_T007_CONST_H .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_YFI_V007_CONST_H-UPD_FLAG,
STATUS_YFI_V007_CONST_H-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_YFI_V007_CONST_H.
  SELECT SINGLE * FROM YFI_T007_CONST_H WHERE
APLICA = YFI_V007_CONST_H-APLICA AND
CGROUP = YFI_V007_CONST_H-CGROUP .
YFI_V007_CONST_H-MANDT =
YFI_T007_CONST_H-MANDT .
YFI_V007_CONST_H-APLICA =
YFI_T007_CONST_H-APLICA .
YFI_V007_CONST_H-CGROUP =
YFI_T007_CONST_H-CGROUP .
YFI_V007_CONST_H-GRPTX =
YFI_T007_CONST_H-GRPTX .
YFI_V007_CONST_H-ACTIV =
YFI_T007_CONST_H-ACTIV .
YFI_V007_CONST_H-ERNAM =
YFI_T007_CONST_H-ERNAM .
YFI_V007_CONST_H-ERDAT =
YFI_T007_CONST_H-ERDAT .
YFI_V007_CONST_H-ERZET =
YFI_T007_CONST_H-ERZET .
YFI_V007_CONST_H-AENAM =
YFI_T007_CONST_H-AENAM .
YFI_V007_CONST_H-AEDAT =
YFI_T007_CONST_H-AEDAT .
YFI_V007_CONST_H-AEZET =
YFI_T007_CONST_H-AEZET .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_YFI_V007_CONST_H USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE YFI_V007_CONST_H-APLICA TO
YFI_T007_CONST_H-APLICA .
MOVE YFI_V007_CONST_H-CGROUP TO
YFI_T007_CONST_H-CGROUP .
MOVE YFI_V007_CONST_H-MANDT TO
YFI_T007_CONST_H-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'YFI_T007_CONST_H'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN YFI_T007_CONST_H TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'YFI_T007_CONST_H'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
