PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_YFI_V008_CONST_D CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD YFI_V008_CONST_D-APLICA .
    FIELD YFI_V008_CONST_D-CGROUP .
    FIELD YFI_V008_CONST_D-CORRE .
    FIELD YFI_V008_CONST_D-ZVALOR .
    FIELD YFI_V008_CONST_D-YVALOR .
    FIELD YFI_V008_CONST_D-XVALOR .
    FIELD YFI_V008_CONST_D-WVALOR .
    FIELD YFI_V008_CONST_D-ACTIV .
    FIELD YFI_V008_CONST_D-ERNAM .
    FIELD YFI_V008_CONST_D-ERDAT .
    FIELD YFI_V008_CONST_D-ERZET .
    FIELD YFI_V008_CONST_D-AENAM .
    FIELD YFI_V008_CONST_D-AEDAT .
    FIELD YFI_V008_CONST_D-AEZET .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD YFI_V008_CONST_D-APLICA .
    FIELD YFI_V008_CONST_D-CGROUP .
    FIELD YFI_V008_CONST_D-CORRE .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
