*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: YFI_V008_CONST_D................................*
FORM GET_DATA_YFI_V008_CONST_D.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM YFI_T008_CONST_D WHERE
(VIM_WHERETAB) .
    CLEAR YFI_V008_CONST_D .
YFI_V008_CONST_D-MANDT =
YFI_T008_CONST_D-MANDT .
YFI_V008_CONST_D-APLICA =
YFI_T008_CONST_D-APLICA .
YFI_V008_CONST_D-CGROUP =
YFI_T008_CONST_D-CGROUP .
YFI_V008_CONST_D-CORRE =
YFI_T008_CONST_D-CORRE .
YFI_V008_CONST_D-ZVALOR =
YFI_T008_CONST_D-ZVALOR .
YFI_V008_CONST_D-YVALOR =
YFI_T008_CONST_D-YVALOR .
YFI_V008_CONST_D-XVALOR =
YFI_T008_CONST_D-XVALOR .
YFI_V008_CONST_D-WVALOR =
YFI_T008_CONST_D-WVALOR .
YFI_V008_CONST_D-ACTIV =
YFI_T008_CONST_D-ACTIV .
YFI_V008_CONST_D-ERNAM =
YFI_T008_CONST_D-ERNAM .
YFI_V008_CONST_D-ERDAT =
YFI_T008_CONST_D-ERDAT .
YFI_V008_CONST_D-ERZET =
YFI_T008_CONST_D-ERZET .
YFI_V008_CONST_D-AENAM =
YFI_T008_CONST_D-AENAM .
YFI_V008_CONST_D-AEDAT =
YFI_T008_CONST_D-AEDAT .
YFI_V008_CONST_D-AEZET =
YFI_T008_CONST_D-AEZET .
<VIM_TOTAL_STRUC> = YFI_V008_CONST_D.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_YFI_V008_CONST_D .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO YFI_V008_CONST_D.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_YFI_V008_CONST_D-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM YFI_T008_CONST_D WHERE
  APLICA = YFI_V008_CONST_D-APLICA AND
  CGROUP = YFI_V008_CONST_D-CGROUP AND
  CORRE = YFI_V008_CONST_D-CORRE .
    IF SY-SUBRC = 0.
    DELETE YFI_T008_CONST_D .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM YFI_T008_CONST_D WHERE
  APLICA = YFI_V008_CONST_D-APLICA AND
  CGROUP = YFI_V008_CONST_D-CGROUP AND
  CORRE = YFI_V008_CONST_D-CORRE .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR YFI_T008_CONST_D.
    ENDIF.
YFI_T008_CONST_D-MANDT =
YFI_V008_CONST_D-MANDT .
YFI_T008_CONST_D-APLICA =
YFI_V008_CONST_D-APLICA .
YFI_T008_CONST_D-CGROUP =
YFI_V008_CONST_D-CGROUP .
YFI_T008_CONST_D-CORRE =
YFI_V008_CONST_D-CORRE .
YFI_T008_CONST_D-ZVALOR =
YFI_V008_CONST_D-ZVALOR .
YFI_T008_CONST_D-YVALOR =
YFI_V008_CONST_D-YVALOR .
YFI_T008_CONST_D-XVALOR =
YFI_V008_CONST_D-XVALOR .
YFI_T008_CONST_D-WVALOR =
YFI_V008_CONST_D-WVALOR .
YFI_T008_CONST_D-ACTIV =
YFI_V008_CONST_D-ACTIV .
YFI_T008_CONST_D-ERNAM =
YFI_V008_CONST_D-ERNAM .
YFI_T008_CONST_D-ERDAT =
YFI_V008_CONST_D-ERDAT .
YFI_T008_CONST_D-ERZET =
YFI_V008_CONST_D-ERZET .
YFI_T008_CONST_D-AENAM =
YFI_V008_CONST_D-AENAM .
YFI_T008_CONST_D-AEDAT =
YFI_V008_CONST_D-AEDAT .
YFI_T008_CONST_D-AEZET =
YFI_V008_CONST_D-AEZET .
    IF SY-SUBRC = 0.
    UPDATE YFI_T008_CONST_D ##WARN_OK.
    ELSE.
    INSERT YFI_T008_CONST_D .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_YFI_V008_CONST_D-UPD_FLAG,
STATUS_YFI_V008_CONST_D-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_YFI_V008_CONST_D.
  SELECT SINGLE * FROM YFI_T008_CONST_D WHERE
APLICA = YFI_V008_CONST_D-APLICA AND
CGROUP = YFI_V008_CONST_D-CGROUP AND
CORRE = YFI_V008_CONST_D-CORRE .
YFI_V008_CONST_D-MANDT =
YFI_T008_CONST_D-MANDT .
YFI_V008_CONST_D-APLICA =
YFI_T008_CONST_D-APLICA .
YFI_V008_CONST_D-CGROUP =
YFI_T008_CONST_D-CGROUP .
YFI_V008_CONST_D-CORRE =
YFI_T008_CONST_D-CORRE .
YFI_V008_CONST_D-ZVALOR =
YFI_T008_CONST_D-ZVALOR .
YFI_V008_CONST_D-YVALOR =
YFI_T008_CONST_D-YVALOR .
YFI_V008_CONST_D-XVALOR =
YFI_T008_CONST_D-XVALOR .
YFI_V008_CONST_D-WVALOR =
YFI_T008_CONST_D-WVALOR .
YFI_V008_CONST_D-ACTIV =
YFI_T008_CONST_D-ACTIV .
YFI_V008_CONST_D-ERNAM =
YFI_T008_CONST_D-ERNAM .
YFI_V008_CONST_D-ERDAT =
YFI_T008_CONST_D-ERDAT .
YFI_V008_CONST_D-ERZET =
YFI_T008_CONST_D-ERZET .
YFI_V008_CONST_D-AENAM =
YFI_T008_CONST_D-AENAM .
YFI_V008_CONST_D-AEDAT =
YFI_T008_CONST_D-AEDAT .
YFI_V008_CONST_D-AEZET =
YFI_T008_CONST_D-AEZET .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_YFI_V008_CONST_D USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE YFI_V008_CONST_D-APLICA TO
YFI_T008_CONST_D-APLICA .
MOVE YFI_V008_CONST_D-CGROUP TO
YFI_T008_CONST_D-CGROUP .
MOVE YFI_V008_CONST_D-CORRE TO
YFI_T008_CONST_D-CORRE .
MOVE YFI_V008_CONST_D-MANDT TO
YFI_T008_CONST_D-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'YFI_T008_CONST_D'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN YFI_T008_CONST_D TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'YFI_T008_CONST_D'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
