*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: YFI_V002_CTACAJA................................*
FORM GET_DATA_YFI_V002_CTACAJA.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM YFI_T002_CTACAJA WHERE
(VIM_WHERETAB) .
    CLEAR YFI_V002_CTACAJA .
YFI_V002_CTACAJA-MANDT =
YFI_T002_CTACAJA-MANDT .
YFI_V002_CTACAJA-CJ_SOC =
YFI_T002_CTACAJA-CJ_SOC .
YFI_V002_CTACAJA-CJ_MM =
YFI_T002_CTACAJA-CJ_MM .
YFI_V002_CTACAJA-CJ_ME =
YFI_T002_CTACAJA-CJ_ME .
YFI_V002_CTACAJA-CJ_TXT =
YFI_T002_CTACAJA-CJ_TXT .
YFI_V002_CTACAJA-CJ_COB =
YFI_T002_CTACAJA-CJ_COB .
YFI_V002_CTACAJA-CJ_CENTRAL =
YFI_T002_CTACAJA-CJ_CENTRAL .
YFI_V002_CTACAJA-UNAME =
YFI_T002_CTACAJA-UNAME .
YFI_V002_CTACAJA-AEDTM =
YFI_T002_CTACAJA-AEDTM .
YFI_V002_CTACAJA-UZEIT =
YFI_T002_CTACAJA-UZEIT .
<VIM_TOTAL_STRUC> = YFI_V002_CTACAJA.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_YFI_V002_CTACAJA .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO YFI_V002_CTACAJA.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_YFI_V002_CTACAJA-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM YFI_T002_CTACAJA WHERE
  CJ_SOC = YFI_V002_CTACAJA-CJ_SOC AND
  CJ_MM = YFI_V002_CTACAJA-CJ_MM .
    IF SY-SUBRC = 0.
    DELETE YFI_T002_CTACAJA .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM YFI_T002_CTACAJA WHERE
  CJ_SOC = YFI_V002_CTACAJA-CJ_SOC AND
  CJ_MM = YFI_V002_CTACAJA-CJ_MM .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR YFI_T002_CTACAJA.
    ENDIF.
YFI_T002_CTACAJA-MANDT =
YFI_V002_CTACAJA-MANDT .
YFI_T002_CTACAJA-CJ_SOC =
YFI_V002_CTACAJA-CJ_SOC .
YFI_T002_CTACAJA-CJ_MM =
YFI_V002_CTACAJA-CJ_MM .
YFI_T002_CTACAJA-CJ_ME =
YFI_V002_CTACAJA-CJ_ME .
YFI_T002_CTACAJA-CJ_TXT =
YFI_V002_CTACAJA-CJ_TXT .
YFI_T002_CTACAJA-CJ_COB =
YFI_V002_CTACAJA-CJ_COB .
YFI_T002_CTACAJA-CJ_CENTRAL =
YFI_V002_CTACAJA-CJ_CENTRAL .
YFI_T002_CTACAJA-UNAME =
YFI_V002_CTACAJA-UNAME .
YFI_T002_CTACAJA-AEDTM =
YFI_V002_CTACAJA-AEDTM .
YFI_T002_CTACAJA-UZEIT =
YFI_V002_CTACAJA-UZEIT .
    IF SY-SUBRC = 0.
    UPDATE YFI_T002_CTACAJA ##WARN_OK.
    ELSE.
    INSERT YFI_T002_CTACAJA .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_YFI_V002_CTACAJA-UPD_FLAG,
STATUS_YFI_V002_CTACAJA-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_YFI_V002_CTACAJA.
  SELECT SINGLE * FROM YFI_T002_CTACAJA WHERE
CJ_SOC = YFI_V002_CTACAJA-CJ_SOC AND
CJ_MM = YFI_V002_CTACAJA-CJ_MM .
YFI_V002_CTACAJA-MANDT =
YFI_T002_CTACAJA-MANDT .
YFI_V002_CTACAJA-CJ_SOC =
YFI_T002_CTACAJA-CJ_SOC .
YFI_V002_CTACAJA-CJ_MM =
YFI_T002_CTACAJA-CJ_MM .
YFI_V002_CTACAJA-CJ_ME =
YFI_T002_CTACAJA-CJ_ME .
YFI_V002_CTACAJA-CJ_TXT =
YFI_T002_CTACAJA-CJ_TXT .
YFI_V002_CTACAJA-CJ_COB =
YFI_T002_CTACAJA-CJ_COB .
YFI_V002_CTACAJA-CJ_CENTRAL =
YFI_T002_CTACAJA-CJ_CENTRAL .
YFI_V002_CTACAJA-UNAME =
YFI_T002_CTACAJA-UNAME .
YFI_V002_CTACAJA-AEDTM =
YFI_T002_CTACAJA-AEDTM .
YFI_V002_CTACAJA-UZEIT =
YFI_T002_CTACAJA-UZEIT .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_YFI_V002_CTACAJA USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE YFI_V002_CTACAJA-CJ_SOC TO
YFI_T002_CTACAJA-CJ_SOC .
MOVE YFI_V002_CTACAJA-CJ_MM TO
YFI_T002_CTACAJA-CJ_MM .
MOVE YFI_V002_CTACAJA-MANDT TO
YFI_T002_CTACAJA-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'YFI_T002_CTACAJA'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN YFI_T002_CTACAJA TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'YFI_T002_CTACAJA'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
