PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_YFI_V001_METPAGO CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD YFI_V001_METPAGO-VKORG .
    FIELD YFI_V001_METPAGO-MET_PAG .
    FIELD YFI_V001_METPAGO-TXT_PAG .
    FIELD YFI_V001_METPAGO-PAS_PAG .
    FIELD YFI_V001_METPAGO-VIA_PAGO .
    FIELD YFI_V001_METPAGO-UNAME .
    FIELD YFI_V001_METPAGO-AEDTM .
    FIELD YFI_V001_METPAGO-UZEIT .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD YFI_V001_METPAGO-VKORG .
    FIELD YFI_V001_METPAGO-MET_PAG .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
