PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_YFI_V003_CTABCOS CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD YFI_V003_CTABCOS-SOC_BCO .
    FIELD YFI_V003_CTABCOS-CTA_BCO .
    FIELD YFI_V003_CTABCOS-TXT_BCO .
    FIELD YFI_V003_CTABCOS-MON_BCO .
    FIELD YFI_V003_CTABCOS-CCH_BCO .
    FIELD YFI_V003_CTABCOS-UNAME .
    FIELD YFI_V003_CTABCOS-AEDTM .
    FIELD YFI_V003_CTABCOS-UZEIT .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD YFI_V003_CTABCOS-SOC_BCO .
    FIELD YFI_V003_CTABCOS-CTA_BCO .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
