PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_YFI_V002_CTACAJA CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD YFI_V002_CTACAJA-CJ_SOC .
    FIELD YFI_V002_CTACAJA-CJ_MM .
    FIELD YFI_V002_CTACAJA-CJ_ME .
    FIELD YFI_V002_CTACAJA-CJ_TXT .
    FIELD YFI_V002_CTACAJA-CJ_COB .
    FIELD YFI_V002_CTACAJA-CJ_CENTRAL .
    FIELD YFI_V002_CTACAJA-UNAME .
    FIELD YFI_V002_CTACAJA-AEDTM .
    FIELD YFI_V002_CTACAJA-UZEIT .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD YFI_V002_CTACAJA-CJ_SOC .
    FIELD YFI_V002_CTACAJA-CJ_MM .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
