*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: YFI_V003_CTABCOS................................*
FORM GET_DATA_YFI_V003_CTABCOS.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM YFI_T003_CTABCOS WHERE
(VIM_WHERETAB) .
    CLEAR YFI_V003_CTABCOS .
YFI_V003_CTABCOS-MANDT =
YFI_T003_CTABCOS-MANDT .
YFI_V003_CTABCOS-SOC_BCO =
YFI_T003_CTABCOS-SOC_BCO .
YFI_V003_CTABCOS-CTA_BCO =
YFI_T003_CTABCOS-CTA_BCO .
YFI_V003_CTABCOS-TXT_BCO =
YFI_T003_CTABCOS-TXT_BCO .
YFI_V003_CTABCOS-MON_BCO =
YFI_T003_CTABCOS-MON_BCO .
YFI_V003_CTABCOS-CCH_BCO =
YFI_T003_CTABCOS-CCH_BCO .
YFI_V003_CTABCOS-UNAME =
YFI_T003_CTABCOS-UNAME .
YFI_V003_CTABCOS-AEDTM =
YFI_T003_CTABCOS-AEDTM .
YFI_V003_CTABCOS-UZEIT =
YFI_T003_CTABCOS-UZEIT .
<VIM_TOTAL_STRUC> = YFI_V003_CTABCOS.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_YFI_V003_CTABCOS .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO YFI_V003_CTABCOS.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_YFI_V003_CTABCOS-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM YFI_T003_CTABCOS WHERE
  SOC_BCO = YFI_V003_CTABCOS-SOC_BCO AND
  CTA_BCO = YFI_V003_CTABCOS-CTA_BCO .
    IF SY-SUBRC = 0.
    DELETE YFI_T003_CTABCOS .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM YFI_T003_CTABCOS WHERE
  SOC_BCO = YFI_V003_CTABCOS-SOC_BCO AND
  CTA_BCO = YFI_V003_CTABCOS-CTA_BCO .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR YFI_T003_CTABCOS.
    ENDIF.
YFI_T003_CTABCOS-MANDT =
YFI_V003_CTABCOS-MANDT .
YFI_T003_CTABCOS-SOC_BCO =
YFI_V003_CTABCOS-SOC_BCO .
YFI_T003_CTABCOS-CTA_BCO =
YFI_V003_CTABCOS-CTA_BCO .
YFI_T003_CTABCOS-TXT_BCO =
YFI_V003_CTABCOS-TXT_BCO .
YFI_T003_CTABCOS-MON_BCO =
YFI_V003_CTABCOS-MON_BCO .
YFI_T003_CTABCOS-CCH_BCO =
YFI_V003_CTABCOS-CCH_BCO .
YFI_T003_CTABCOS-UNAME =
YFI_V003_CTABCOS-UNAME .
YFI_T003_CTABCOS-AEDTM =
YFI_V003_CTABCOS-AEDTM .
YFI_T003_CTABCOS-UZEIT =
YFI_V003_CTABCOS-UZEIT .
    IF SY-SUBRC = 0.
    UPDATE YFI_T003_CTABCOS ##WARN_OK.
    ELSE.
    INSERT YFI_T003_CTABCOS .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_YFI_V003_CTABCOS-UPD_FLAG,
STATUS_YFI_V003_CTABCOS-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_YFI_V003_CTABCOS.
  SELECT SINGLE * FROM YFI_T003_CTABCOS WHERE
SOC_BCO = YFI_V003_CTABCOS-SOC_BCO AND
CTA_BCO = YFI_V003_CTABCOS-CTA_BCO .
YFI_V003_CTABCOS-MANDT =
YFI_T003_CTABCOS-MANDT .
YFI_V003_CTABCOS-SOC_BCO =
YFI_T003_CTABCOS-SOC_BCO .
YFI_V003_CTABCOS-CTA_BCO =
YFI_T003_CTABCOS-CTA_BCO .
YFI_V003_CTABCOS-TXT_BCO =
YFI_T003_CTABCOS-TXT_BCO .
YFI_V003_CTABCOS-MON_BCO =
YFI_T003_CTABCOS-MON_BCO .
YFI_V003_CTABCOS-CCH_BCO =
YFI_T003_CTABCOS-CCH_BCO .
YFI_V003_CTABCOS-UNAME =
YFI_T003_CTABCOS-UNAME .
YFI_V003_CTABCOS-AEDTM =
YFI_T003_CTABCOS-AEDTM .
YFI_V003_CTABCOS-UZEIT =
YFI_T003_CTABCOS-UZEIT .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_YFI_V003_CTABCOS USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE YFI_V003_CTABCOS-SOC_BCO TO
YFI_T003_CTABCOS-SOC_BCO .
MOVE YFI_V003_CTABCOS-CTA_BCO TO
YFI_T003_CTABCOS-CTA_BCO .
MOVE YFI_V003_CTABCOS-MANDT TO
YFI_T003_CTABCOS-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'YFI_T003_CTABCOS'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN YFI_T003_CTABCOS TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'YFI_T003_CTABCOS'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
