PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_YSD_V006_RCONDIC CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD YSD_V006_RCONDIC-AUART .
    FIELD YSD_V006_RCONDIC-KSCHL .
    FIELD YSD_V006_RCONDIC-MATKL .
    FIELD YSD_V006_RCONDIC-BNAME .
    FIELD YSD_V006_RCONDIC-KBETRA .
    FIELD YSD_V006_RCONDIC-KBETRB .
    FIELD YSD_V006_RCONDIC-ZZSD_TOLERANCIA .
    FIELD YSD_V006_RCONDIC-UNAME .
    FIELD YSD_V006_RCONDIC-AEDTM .
    FIELD YSD_V006_RCONDIC-UZEIT .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD YSD_V006_RCONDIC-AUART .
    FIELD YSD_V006_RCONDIC-KSCHL .
    FIELD YSD_V006_RCONDIC-MATKL .
    FIELD YSD_V006_RCONDIC-BNAME .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
