PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_YSD_V005_TOLERAN CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD YSD_V005_TOLERAN-VKORG .
    FIELD YSD_V005_TOLERAN-KSCHL .
    FIELD YSD_V005_TOLERAN-TOLERANCIA_A .
    FIELD YSD_V005_TOLERAN-TOLERANCIA_B .
    FIELD YSD_V005_TOLERAN-UNAME .
    FIELD YSD_V005_TOLERAN-AEDTM .
    FIELD YSD_V005_TOLERAN-UZEIT .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD YSD_V005_TOLERAN-VKORG .
    FIELD YSD_V005_TOLERAN-KSCHL .
    FIELD YSD_V005_TOLERAN-TOLERANCIA_A .
    FIELD YSD_V005_TOLERAN-TOLERANCIA_B .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
