*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: YSD_V001_PARAMET................................*
FORM GET_DATA_YSD_V001_PARAMET.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM YSD_T001_PARAMET WHERE
(VIM_WHERETAB) .
    CLEAR YSD_V001_PARAMET .
YSD_V001_PARAMET-MANDT =
YSD_T001_PARAMET-MANDT .
YSD_V001_PARAMET-DOC_TYPE_C =
YSD_T001_PARAMET-DOC_TYPE_C .
YSD_V001_PARAMET-DOC_TYPE_P =
YSD_T001_PARAMET-DOC_TYPE_P .
YSD_V001_PARAMET-DOC_TYPE_F =
YSD_T001_PARAMET-DOC_TYPE_F .
YSD_V001_PARAMET-INDI_EXPEDI =
YSD_T001_PARAMET-INDI_EXPEDI .
YSD_V001_PARAMET-FACTURACION =
YSD_T001_PARAMET-FACTURACION .
YSD_V001_PARAMET-VKORG =
YSD_T001_PARAMET-VKORG .
YSD_V001_PARAMET-UNAME =
YSD_T001_PARAMET-UNAME .
YSD_V001_PARAMET-AEDTM =
YSD_T001_PARAMET-AEDTM .
YSD_V001_PARAMET-UZEIT =
YSD_T001_PARAMET-UZEIT .
<VIM_TOTAL_STRUC> = YSD_V001_PARAMET.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_YSD_V001_PARAMET .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO YSD_V001_PARAMET.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_YSD_V001_PARAMET-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM YSD_T001_PARAMET WHERE
  DOC_TYPE_C = YSD_V001_PARAMET-DOC_TYPE_C AND
  DOC_TYPE_P = YSD_V001_PARAMET-DOC_TYPE_P AND
  DOC_TYPE_F = YSD_V001_PARAMET-DOC_TYPE_F AND
  INDI_EXPEDI = YSD_V001_PARAMET-INDI_EXPEDI AND
  FACTURACION = YSD_V001_PARAMET-FACTURACION AND
  VKORG = YSD_V001_PARAMET-VKORG .
    IF SY-SUBRC = 0.
    DELETE YSD_T001_PARAMET .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM YSD_T001_PARAMET WHERE
  DOC_TYPE_C = YSD_V001_PARAMET-DOC_TYPE_C AND
  DOC_TYPE_P = YSD_V001_PARAMET-DOC_TYPE_P AND
  DOC_TYPE_F = YSD_V001_PARAMET-DOC_TYPE_F AND
  INDI_EXPEDI = YSD_V001_PARAMET-INDI_EXPEDI AND
  FACTURACION = YSD_V001_PARAMET-FACTURACION AND
  VKORG = YSD_V001_PARAMET-VKORG .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR YSD_T001_PARAMET.
    ENDIF.
YSD_T001_PARAMET-MANDT =
YSD_V001_PARAMET-MANDT .
YSD_T001_PARAMET-DOC_TYPE_C =
YSD_V001_PARAMET-DOC_TYPE_C .
YSD_T001_PARAMET-DOC_TYPE_P =
YSD_V001_PARAMET-DOC_TYPE_P .
YSD_T001_PARAMET-DOC_TYPE_F =
YSD_V001_PARAMET-DOC_TYPE_F .
YSD_T001_PARAMET-INDI_EXPEDI =
YSD_V001_PARAMET-INDI_EXPEDI .
YSD_T001_PARAMET-FACTURACION =
YSD_V001_PARAMET-FACTURACION .
YSD_T001_PARAMET-VKORG =
YSD_V001_PARAMET-VKORG .
YSD_T001_PARAMET-UNAME =
YSD_V001_PARAMET-UNAME .
YSD_T001_PARAMET-AEDTM =
YSD_V001_PARAMET-AEDTM .
YSD_T001_PARAMET-UZEIT =
YSD_V001_PARAMET-UZEIT .
    IF SY-SUBRC = 0.
    UPDATE YSD_T001_PARAMET ##WARN_OK.
    ELSE.
    INSERT YSD_T001_PARAMET .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_YSD_V001_PARAMET-UPD_FLAG,
STATUS_YSD_V001_PARAMET-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_YSD_V001_PARAMET.
  SELECT SINGLE * FROM YSD_T001_PARAMET WHERE
DOC_TYPE_C = YSD_V001_PARAMET-DOC_TYPE_C AND
DOC_TYPE_P = YSD_V001_PARAMET-DOC_TYPE_P AND
DOC_TYPE_F = YSD_V001_PARAMET-DOC_TYPE_F AND
INDI_EXPEDI = YSD_V001_PARAMET-INDI_EXPEDI AND
FACTURACION = YSD_V001_PARAMET-FACTURACION AND
VKORG = YSD_V001_PARAMET-VKORG .
YSD_V001_PARAMET-MANDT =
YSD_T001_PARAMET-MANDT .
YSD_V001_PARAMET-DOC_TYPE_C =
YSD_T001_PARAMET-DOC_TYPE_C .
YSD_V001_PARAMET-DOC_TYPE_P =
YSD_T001_PARAMET-DOC_TYPE_P .
YSD_V001_PARAMET-DOC_TYPE_F =
YSD_T001_PARAMET-DOC_TYPE_F .
YSD_V001_PARAMET-INDI_EXPEDI =
YSD_T001_PARAMET-INDI_EXPEDI .
YSD_V001_PARAMET-FACTURACION =
YSD_T001_PARAMET-FACTURACION .
YSD_V001_PARAMET-VKORG =
YSD_T001_PARAMET-VKORG .
YSD_V001_PARAMET-UNAME =
YSD_T001_PARAMET-UNAME .
YSD_V001_PARAMET-AEDTM =
YSD_T001_PARAMET-AEDTM .
YSD_V001_PARAMET-UZEIT =
YSD_T001_PARAMET-UZEIT .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_YSD_V001_PARAMET USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE YSD_V001_PARAMET-DOC_TYPE_C TO
YSD_T001_PARAMET-DOC_TYPE_C .
MOVE YSD_V001_PARAMET-DOC_TYPE_P TO
YSD_T001_PARAMET-DOC_TYPE_P .
MOVE YSD_V001_PARAMET-DOC_TYPE_F TO
YSD_T001_PARAMET-DOC_TYPE_F .
MOVE YSD_V001_PARAMET-INDI_EXPEDI TO
YSD_T001_PARAMET-INDI_EXPEDI .
MOVE YSD_V001_PARAMET-FACTURACION TO
YSD_T001_PARAMET-FACTURACION .
MOVE YSD_V001_PARAMET-VKORG TO
YSD_T001_PARAMET-VKORG .
MOVE YSD_V001_PARAMET-MANDT TO
YSD_T001_PARAMET-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'YSD_T001_PARAMET'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN YSD_T001_PARAMET TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'YSD_T001_PARAMET'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
