*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: YSD_V006_RCONDIC................................*
FORM GET_DATA_YSD_V006_RCONDIC.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM YSD_T006_RCONDIC WHERE
(VIM_WHERETAB) .
    CLEAR YSD_V006_RCONDIC .
YSD_V006_RCONDIC-MANDT =
YSD_T006_RCONDIC-MANDT .
YSD_V006_RCONDIC-AUART =
YSD_T006_RCONDIC-AUART .
YSD_V006_RCONDIC-KSCHL =
YSD_T006_RCONDIC-KSCHL .
YSD_V006_RCONDIC-MATKL =
YSD_T006_RCONDIC-MATKL .
YSD_V006_RCONDIC-BNAME =
YSD_T006_RCONDIC-BNAME .
YSD_V006_RCONDIC-KBETRA =
YSD_T006_RCONDIC-KBETRA .
YSD_V006_RCONDIC-KBETRB =
YSD_T006_RCONDIC-KBETRB .
YSD_V006_RCONDIC-ZZSD_TOLERANCIA =
YSD_T006_RCONDIC-ZZSD_TOLERANCIA .
YSD_V006_RCONDIC-UNAME =
YSD_T006_RCONDIC-UNAME .
YSD_V006_RCONDIC-AEDTM =
YSD_T006_RCONDIC-AEDTM .
YSD_V006_RCONDIC-UZEIT =
YSD_T006_RCONDIC-UZEIT .
<VIM_TOTAL_STRUC> = YSD_V006_RCONDIC.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_YSD_V006_RCONDIC .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO YSD_V006_RCONDIC.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_YSD_V006_RCONDIC-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM YSD_T006_RCONDIC WHERE
  AUART = YSD_V006_RCONDIC-AUART AND
  KSCHL = YSD_V006_RCONDIC-KSCHL AND
  MATKL = YSD_V006_RCONDIC-MATKL AND
  BNAME = YSD_V006_RCONDIC-BNAME .
    IF SY-SUBRC = 0.
    DELETE YSD_T006_RCONDIC .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM YSD_T006_RCONDIC WHERE
  AUART = YSD_V006_RCONDIC-AUART AND
  KSCHL = YSD_V006_RCONDIC-KSCHL AND
  MATKL = YSD_V006_RCONDIC-MATKL AND
  BNAME = YSD_V006_RCONDIC-BNAME .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR YSD_T006_RCONDIC.
    ENDIF.
YSD_T006_RCONDIC-MANDT =
YSD_V006_RCONDIC-MANDT .
YSD_T006_RCONDIC-AUART =
YSD_V006_RCONDIC-AUART .
YSD_T006_RCONDIC-KSCHL =
YSD_V006_RCONDIC-KSCHL .
YSD_T006_RCONDIC-MATKL =
YSD_V006_RCONDIC-MATKL .
YSD_T006_RCONDIC-BNAME =
YSD_V006_RCONDIC-BNAME .
YSD_T006_RCONDIC-KBETRA =
YSD_V006_RCONDIC-KBETRA .
YSD_T006_RCONDIC-KBETRB =
YSD_V006_RCONDIC-KBETRB .
YSD_T006_RCONDIC-ZZSD_TOLERANCIA =
YSD_V006_RCONDIC-ZZSD_TOLERANCIA .
YSD_T006_RCONDIC-UNAME =
YSD_V006_RCONDIC-UNAME .
YSD_T006_RCONDIC-AEDTM =
YSD_V006_RCONDIC-AEDTM .
YSD_T006_RCONDIC-UZEIT =
YSD_V006_RCONDIC-UZEIT .
    IF SY-SUBRC = 0.
    UPDATE YSD_T006_RCONDIC ##WARN_OK.
    ELSE.
    INSERT YSD_T006_RCONDIC .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_YSD_V006_RCONDIC-UPD_FLAG,
STATUS_YSD_V006_RCONDIC-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_YSD_V006_RCONDIC.
  SELECT SINGLE * FROM YSD_T006_RCONDIC WHERE
AUART = YSD_V006_RCONDIC-AUART AND
KSCHL = YSD_V006_RCONDIC-KSCHL AND
MATKL = YSD_V006_RCONDIC-MATKL AND
BNAME = YSD_V006_RCONDIC-BNAME .
YSD_V006_RCONDIC-MANDT =
YSD_T006_RCONDIC-MANDT .
YSD_V006_RCONDIC-AUART =
YSD_T006_RCONDIC-AUART .
YSD_V006_RCONDIC-KSCHL =
YSD_T006_RCONDIC-KSCHL .
YSD_V006_RCONDIC-MATKL =
YSD_T006_RCONDIC-MATKL .
YSD_V006_RCONDIC-BNAME =
YSD_T006_RCONDIC-BNAME .
YSD_V006_RCONDIC-KBETRA =
YSD_T006_RCONDIC-KBETRA .
YSD_V006_RCONDIC-KBETRB =
YSD_T006_RCONDIC-KBETRB .
YSD_V006_RCONDIC-ZZSD_TOLERANCIA =
YSD_T006_RCONDIC-ZZSD_TOLERANCIA .
YSD_V006_RCONDIC-UNAME =
YSD_T006_RCONDIC-UNAME .
YSD_V006_RCONDIC-AEDTM =
YSD_T006_RCONDIC-AEDTM .
YSD_V006_RCONDIC-UZEIT =
YSD_T006_RCONDIC-UZEIT .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_YSD_V006_RCONDIC USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE YSD_V006_RCONDIC-AUART TO
YSD_T006_RCONDIC-AUART .
MOVE YSD_V006_RCONDIC-KSCHL TO
YSD_T006_RCONDIC-KSCHL .
MOVE YSD_V006_RCONDIC-MATKL TO
YSD_T006_RCONDIC-MATKL .
MOVE YSD_V006_RCONDIC-BNAME TO
YSD_T006_RCONDIC-BNAME .
MOVE YSD_V006_RCONDIC-MANDT TO
YSD_T006_RCONDIC-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'YSD_T006_RCONDIC'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN YSD_T006_RCONDIC TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'YSD_T006_RCONDIC'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
