*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: YSD_V004_VALMACE................................*
FORM GET_DATA_YSD_V004_VALMACE.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM YSD_T004_VALMACE WHERE
(VIM_WHERETAB) .
    CLEAR YSD_V004_VALMACE .
YSD_V004_VALMACE-MANDT =
YSD_T004_VALMACE-MANDT .
YSD_V004_VALMACE-VKORG =
YSD_T004_VALMACE-VKORG .
YSD_V004_VALMACE-WERKS =
YSD_T004_VALMACE-WERKS .
YSD_V004_VALMACE-SELECTION =
YSD_T004_VALMACE-SELECTION .
YSD_V004_VALMACE-UNAME =
YSD_T004_VALMACE-UNAME .
YSD_V004_VALMACE-AEDTM =
YSD_T004_VALMACE-AEDTM .
YSD_V004_VALMACE-UZEIT =
YSD_T004_VALMACE-UZEIT .
<VIM_TOTAL_STRUC> = YSD_V004_VALMACE.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_YSD_V004_VALMACE .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO YSD_V004_VALMACE.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_YSD_V004_VALMACE-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM YSD_T004_VALMACE WHERE
  VKORG = YSD_V004_VALMACE-VKORG AND
  WERKS = YSD_V004_VALMACE-WERKS .
    IF SY-SUBRC = 0.
    DELETE YSD_T004_VALMACE .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM YSD_T004_VALMACE WHERE
  VKORG = YSD_V004_VALMACE-VKORG AND
  WERKS = YSD_V004_VALMACE-WERKS .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR YSD_T004_VALMACE.
    ENDIF.
YSD_T004_VALMACE-MANDT =
YSD_V004_VALMACE-MANDT .
YSD_T004_VALMACE-VKORG =
YSD_V004_VALMACE-VKORG .
YSD_T004_VALMACE-WERKS =
YSD_V004_VALMACE-WERKS .
YSD_T004_VALMACE-SELECTION =
YSD_V004_VALMACE-SELECTION .
YSD_T004_VALMACE-UNAME =
YSD_V004_VALMACE-UNAME .
YSD_T004_VALMACE-AEDTM =
YSD_V004_VALMACE-AEDTM .
YSD_T004_VALMACE-UZEIT =
YSD_V004_VALMACE-UZEIT .
    IF SY-SUBRC = 0.
    UPDATE YSD_T004_VALMACE ##WARN_OK.
    ELSE.
    INSERT YSD_T004_VALMACE .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_YSD_V004_VALMACE-UPD_FLAG,
STATUS_YSD_V004_VALMACE-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_YSD_V004_VALMACE.
  SELECT SINGLE * FROM YSD_T004_VALMACE WHERE
VKORG = YSD_V004_VALMACE-VKORG AND
WERKS = YSD_V004_VALMACE-WERKS .
YSD_V004_VALMACE-MANDT =
YSD_T004_VALMACE-MANDT .
YSD_V004_VALMACE-VKORG =
YSD_T004_VALMACE-VKORG .
YSD_V004_VALMACE-WERKS =
YSD_T004_VALMACE-WERKS .
YSD_V004_VALMACE-SELECTION =
YSD_T004_VALMACE-SELECTION .
YSD_V004_VALMACE-UNAME =
YSD_T004_VALMACE-UNAME .
YSD_V004_VALMACE-AEDTM =
YSD_T004_VALMACE-AEDTM .
YSD_V004_VALMACE-UZEIT =
YSD_T004_VALMACE-UZEIT .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_YSD_V004_VALMACE USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE YSD_V004_VALMACE-VKORG TO
YSD_T004_VALMACE-VKORG .
MOVE YSD_V004_VALMACE-WERKS TO
YSD_T004_VALMACE-WERKS .
MOVE YSD_V004_VALMACE-MANDT TO
YSD_T004_VALMACE-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'YSD_T004_VALMACE'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN YSD_T004_VALMACE TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'YSD_T004_VALMACE'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
