*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: YSD_V003_DESCUEN................................*
FORM GET_DATA_YSD_V003_DESCUEN.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM YSD_T003_DESCUEN WHERE
(VIM_WHERETAB) .
    CLEAR YSD_V003_DESCUEN .
YSD_V003_DESCUEN-MANDT =
YSD_T003_DESCUEN-MANDT .
YSD_V003_DESCUEN-VKORG =
YSD_T003_DESCUEN-VKORG .
YSD_V003_DESCUEN-TIPODOC =
YSD_T003_DESCUEN-TIPODOC .
YSD_V003_DESCUEN-SECUENCIA =
YSD_T003_DESCUEN-SECUENCIA .
YSD_V003_DESCUEN-KSCHL =
YSD_T003_DESCUEN-KSCHL .
YSD_V003_DESCUEN-VTEXT =
YSD_T003_DESCUEN-VTEXT .
YSD_V003_DESCUEN-KOAID =
YSD_T003_DESCUEN-KOAID .
YSD_V003_DESCUEN-CAMPO_REF =
YSD_T003_DESCUEN-CAMPO_REF .
YSD_V003_DESCUEN-TABLA_REF =
YSD_T003_DESCUEN-TABLA_REF .
YSD_V003_DESCUEN-ACTIVO =
YSD_T003_DESCUEN-ACTIVO .
YSD_V003_DESCUEN-UNAME =
YSD_T003_DESCUEN-UNAME .
YSD_V003_DESCUEN-AEDTM =
YSD_T003_DESCUEN-AEDTM .
YSD_V003_DESCUEN-UZEIT =
YSD_T003_DESCUEN-UZEIT .
<VIM_TOTAL_STRUC> = YSD_V003_DESCUEN.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_YSD_V003_DESCUEN .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO YSD_V003_DESCUEN.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_YSD_V003_DESCUEN-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM YSD_T003_DESCUEN WHERE
  VKORG = YSD_V003_DESCUEN-VKORG AND
  TIPODOC = YSD_V003_DESCUEN-TIPODOC AND
  SECUENCIA = YSD_V003_DESCUEN-SECUENCIA AND
  KSCHL = YSD_V003_DESCUEN-KSCHL .
    IF SY-SUBRC = 0.
    DELETE YSD_T003_DESCUEN .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM YSD_T003_DESCUEN WHERE
  VKORG = YSD_V003_DESCUEN-VKORG AND
  TIPODOC = YSD_V003_DESCUEN-TIPODOC AND
  SECUENCIA = YSD_V003_DESCUEN-SECUENCIA AND
  KSCHL = YSD_V003_DESCUEN-KSCHL .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR YSD_T003_DESCUEN.
    ENDIF.
YSD_T003_DESCUEN-MANDT =
YSD_V003_DESCUEN-MANDT .
YSD_T003_DESCUEN-VKORG =
YSD_V003_DESCUEN-VKORG .
YSD_T003_DESCUEN-TIPODOC =
YSD_V003_DESCUEN-TIPODOC .
YSD_T003_DESCUEN-SECUENCIA =
YSD_V003_DESCUEN-SECUENCIA .
YSD_T003_DESCUEN-KSCHL =
YSD_V003_DESCUEN-KSCHL .
YSD_T003_DESCUEN-VTEXT =
YSD_V003_DESCUEN-VTEXT .
YSD_T003_DESCUEN-KOAID =
YSD_V003_DESCUEN-KOAID .
YSD_T003_DESCUEN-CAMPO_REF =
YSD_V003_DESCUEN-CAMPO_REF .
YSD_T003_DESCUEN-TABLA_REF =
YSD_V003_DESCUEN-TABLA_REF .
YSD_T003_DESCUEN-ACTIVO =
YSD_V003_DESCUEN-ACTIVO .
YSD_T003_DESCUEN-UNAME =
YSD_V003_DESCUEN-UNAME .
YSD_T003_DESCUEN-AEDTM =
YSD_V003_DESCUEN-AEDTM .
YSD_T003_DESCUEN-UZEIT =
YSD_V003_DESCUEN-UZEIT .
    IF SY-SUBRC = 0.
    UPDATE YSD_T003_DESCUEN ##WARN_OK.
    ELSE.
    INSERT YSD_T003_DESCUEN .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_YSD_V003_DESCUEN-UPD_FLAG,
STATUS_YSD_V003_DESCUEN-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_YSD_V003_DESCUEN.
  SELECT SINGLE * FROM YSD_T003_DESCUEN WHERE
VKORG = YSD_V003_DESCUEN-VKORG AND
TIPODOC = YSD_V003_DESCUEN-TIPODOC AND
SECUENCIA = YSD_V003_DESCUEN-SECUENCIA AND
KSCHL = YSD_V003_DESCUEN-KSCHL .
YSD_V003_DESCUEN-MANDT =
YSD_T003_DESCUEN-MANDT .
YSD_V003_DESCUEN-VKORG =
YSD_T003_DESCUEN-VKORG .
YSD_V003_DESCUEN-TIPODOC =
YSD_T003_DESCUEN-TIPODOC .
YSD_V003_DESCUEN-SECUENCIA =
YSD_T003_DESCUEN-SECUENCIA .
YSD_V003_DESCUEN-KSCHL =
YSD_T003_DESCUEN-KSCHL .
YSD_V003_DESCUEN-VTEXT =
YSD_T003_DESCUEN-VTEXT .
YSD_V003_DESCUEN-KOAID =
YSD_T003_DESCUEN-KOAID .
YSD_V003_DESCUEN-CAMPO_REF =
YSD_T003_DESCUEN-CAMPO_REF .
YSD_V003_DESCUEN-TABLA_REF =
YSD_T003_DESCUEN-TABLA_REF .
YSD_V003_DESCUEN-ACTIVO =
YSD_T003_DESCUEN-ACTIVO .
YSD_V003_DESCUEN-UNAME =
YSD_T003_DESCUEN-UNAME .
YSD_V003_DESCUEN-AEDTM =
YSD_T003_DESCUEN-AEDTM .
YSD_V003_DESCUEN-UZEIT =
YSD_T003_DESCUEN-UZEIT .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_YSD_V003_DESCUEN USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE YSD_V003_DESCUEN-VKORG TO
YSD_T003_DESCUEN-VKORG .
MOVE YSD_V003_DESCUEN-TIPODOC TO
YSD_T003_DESCUEN-TIPODOC .
MOVE YSD_V003_DESCUEN-SECUENCIA TO
YSD_T003_DESCUEN-SECUENCIA .
MOVE YSD_V003_DESCUEN-KSCHL TO
YSD_T003_DESCUEN-KSCHL .
MOVE YSD_V003_DESCUEN-MANDT TO
YSD_T003_DESCUEN-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'YSD_T003_DESCUEN'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN YSD_T003_DESCUEN TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'YSD_T003_DESCUEN'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
