*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: YSD_V002_TIPOPOS................................*
FORM GET_DATA_YSD_V002_TIPOPOS.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM YSD_T002_TIPOPOS WHERE
(VIM_WHERETAB) .
    CLEAR YSD_V002_TIPOPOS .
YSD_V002_TIPOPOS-MANDT =
YSD_T002_TIPOPOS-MANDT .
YSD_V002_TIPOPOS-DOC_TYPE_P =
YSD_T002_TIPOPOS-DOC_TYPE_P .
YSD_V002_TIPOPOS-MTPOS =
YSD_T002_TIPOPOS-MTPOS .
YSD_V002_TIPOPOS-PSTYV =
YSD_T002_TIPOPOS-PSTYV .
YSD_V002_TIPOPOS-SELECTION =
YSD_T002_TIPOPOS-SELECTION .
YSD_V002_TIPOPOS-UNAME =
YSD_T002_TIPOPOS-UNAME .
YSD_V002_TIPOPOS-AEDTM =
YSD_T002_TIPOPOS-AEDTM .
YSD_V002_TIPOPOS-UZEIT =
YSD_T002_TIPOPOS-UZEIT .
<VIM_TOTAL_STRUC> = YSD_V002_TIPOPOS.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_YSD_V002_TIPOPOS .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO YSD_V002_TIPOPOS.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_YSD_V002_TIPOPOS-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM YSD_T002_TIPOPOS WHERE
  DOC_TYPE_P = YSD_V002_TIPOPOS-DOC_TYPE_P AND
  MTPOS = YSD_V002_TIPOPOS-MTPOS AND
  PSTYV = YSD_V002_TIPOPOS-PSTYV .
    IF SY-SUBRC = 0.
    DELETE YSD_T002_TIPOPOS .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM YSD_T002_TIPOPOS WHERE
  DOC_TYPE_P = YSD_V002_TIPOPOS-DOC_TYPE_P AND
  MTPOS = YSD_V002_TIPOPOS-MTPOS AND
  PSTYV = YSD_V002_TIPOPOS-PSTYV .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR YSD_T002_TIPOPOS.
    ENDIF.
YSD_T002_TIPOPOS-MANDT =
YSD_V002_TIPOPOS-MANDT .
YSD_T002_TIPOPOS-DOC_TYPE_P =
YSD_V002_TIPOPOS-DOC_TYPE_P .
YSD_T002_TIPOPOS-MTPOS =
YSD_V002_TIPOPOS-MTPOS .
YSD_T002_TIPOPOS-PSTYV =
YSD_V002_TIPOPOS-PSTYV .
YSD_T002_TIPOPOS-SELECTION =
YSD_V002_TIPOPOS-SELECTION .
YSD_T002_TIPOPOS-UNAME =
YSD_V002_TIPOPOS-UNAME .
YSD_T002_TIPOPOS-AEDTM =
YSD_V002_TIPOPOS-AEDTM .
YSD_T002_TIPOPOS-UZEIT =
YSD_V002_TIPOPOS-UZEIT .
    IF SY-SUBRC = 0.
    UPDATE YSD_T002_TIPOPOS ##WARN_OK.
    ELSE.
    INSERT YSD_T002_TIPOPOS .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_YSD_V002_TIPOPOS-UPD_FLAG,
STATUS_YSD_V002_TIPOPOS-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_YSD_V002_TIPOPOS.
  SELECT SINGLE * FROM YSD_T002_TIPOPOS WHERE
DOC_TYPE_P = YSD_V002_TIPOPOS-DOC_TYPE_P AND
MTPOS = YSD_V002_TIPOPOS-MTPOS AND
PSTYV = YSD_V002_TIPOPOS-PSTYV .
YSD_V002_TIPOPOS-MANDT =
YSD_T002_TIPOPOS-MANDT .
YSD_V002_TIPOPOS-DOC_TYPE_P =
YSD_T002_TIPOPOS-DOC_TYPE_P .
YSD_V002_TIPOPOS-MTPOS =
YSD_T002_TIPOPOS-MTPOS .
YSD_V002_TIPOPOS-PSTYV =
YSD_T002_TIPOPOS-PSTYV .
YSD_V002_TIPOPOS-SELECTION =
YSD_T002_TIPOPOS-SELECTION .
YSD_V002_TIPOPOS-UNAME =
YSD_T002_TIPOPOS-UNAME .
YSD_V002_TIPOPOS-AEDTM =
YSD_T002_TIPOPOS-AEDTM .
YSD_V002_TIPOPOS-UZEIT =
YSD_T002_TIPOPOS-UZEIT .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_YSD_V002_TIPOPOS USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE YSD_V002_TIPOPOS-DOC_TYPE_P TO
YSD_T002_TIPOPOS-DOC_TYPE_P .
MOVE YSD_V002_TIPOPOS-MTPOS TO
YSD_T002_TIPOPOS-MTPOS .
MOVE YSD_V002_TIPOPOS-PSTYV TO
YSD_T002_TIPOPOS-PSTYV .
MOVE YSD_V002_TIPOPOS-MANDT TO
YSD_T002_TIPOPOS-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'YSD_T002_TIPOPOS'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN YSD_T002_TIPOPOS TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'YSD_T002_TIPOPOS'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
