PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_YSD_V001_PARAMET CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD YSD_V001_PARAMET-DOC_TYPE_C .
    FIELD YSD_V001_PARAMET-DOC_TYPE_P .
    FIELD YSD_V001_PARAMET-DOC_TYPE_F .
    FIELD YSD_V001_PARAMET-INDI_EXPEDI .
    FIELD YSD_V001_PARAMET-FACTURACION .
    FIELD YSD_V001_PARAMET-VKORG .
    FIELD YSD_V001_PARAMET-UNAME .
    FIELD YSD_V001_PARAMET-AEDTM .
    FIELD YSD_V001_PARAMET-UZEIT .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD YSD_V001_PARAMET-DOC_TYPE_C .
    FIELD YSD_V001_PARAMET-DOC_TYPE_P .
    FIELD YSD_V001_PARAMET-DOC_TYPE_F .
    FIELD YSD_V001_PARAMET-INDI_EXPEDI .
    FIELD YSD_V001_PARAMET-FACTURACION .
    FIELD YSD_V001_PARAMET-VKORG .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
