PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_YSD_V003_DESCUEN CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD YSD_V003_DESCUEN-VKORG .
    FIELD YSD_V003_DESCUEN-TIPODOC .
    FIELD YSD_V003_DESCUEN-SECUENCIA .
    FIELD YSD_V003_DESCUEN-KSCHL .
    FIELD YSD_V003_DESCUEN-VTEXT .
    FIELD YSD_V003_DESCUEN-KOAID .
    FIELD YSD_V003_DESCUEN-CAMPO_REF .
    FIELD YSD_V003_DESCUEN-TABLA_REF .
    FIELD YSD_V003_DESCUEN-ACTIVO .
    FIELD YSD_V003_DESCUEN-UNAME .
    FIELD YSD_V003_DESCUEN-AEDTM .
    FIELD YSD_V003_DESCUEN-UZEIT .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD YSD_V003_DESCUEN-VKORG .
    FIELD YSD_V003_DESCUEN-TIPODOC .
    FIELD YSD_V003_DESCUEN-SECUENCIA .
    FIELD YSD_V003_DESCUEN-KSCHL .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
