PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_YSD_V002_TIPOPOS CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD YSD_V002_TIPOPOS-DOC_TYPE_P .
    FIELD YSD_V002_TIPOPOS-MTPOS .
    FIELD YSD_V002_TIPOPOS-PSTYV .
    FIELD YSD_V002_TIPOPOS-SELECTION .
    FIELD YSD_V002_TIPOPOS-UNAME .
    FIELD YSD_V002_TIPOPOS-AEDTM .
    FIELD YSD_V002_TIPOPOS-UZEIT .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD YSD_V002_TIPOPOS-DOC_TYPE_P .
    FIELD YSD_V002_TIPOPOS-MTPOS .
    FIELD YSD_V002_TIPOPOS-PSTYV .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
