*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: YSD_V005_TOLERAN................................*
FORM GET_DATA_YSD_V005_TOLERAN.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM YSD_T005_TOLERAN WHERE
(VIM_WHERETAB) .
    CLEAR YSD_V005_TOLERAN .
YSD_V005_TOLERAN-MANDT =
YSD_T005_TOLERAN-MANDT .
YSD_V005_TOLERAN-VKORG =
YSD_T005_TOLERAN-VKORG .
YSD_V005_TOLERAN-KSCHL =
YSD_T005_TOLERAN-KSCHL .
YSD_V005_TOLERAN-TOLERANCIA_A =
YSD_T005_TOLERAN-TOLERANCIA_A .
YSD_V005_TOLERAN-TOLERANCIA_B =
YSD_T005_TOLERAN-TOLERANCIA_B .
YSD_V005_TOLERAN-UNAME =
YSD_T005_TOLERAN-UNAME .
YSD_V005_TOLERAN-AEDTM =
YSD_T005_TOLERAN-AEDTM .
YSD_V005_TOLERAN-UZEIT =
YSD_T005_TOLERAN-UZEIT .
<VIM_TOTAL_STRUC> = YSD_V005_TOLERAN.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_YSD_V005_TOLERAN .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO YSD_V005_TOLERAN.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_YSD_V005_TOLERAN-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM YSD_T005_TOLERAN WHERE
  VKORG = YSD_V005_TOLERAN-VKORG AND
  KSCHL = YSD_V005_TOLERAN-KSCHL AND
  TOLERANCIA_A = YSD_V005_TOLERAN-TOLERANCIA_A AND
  TOLERANCIA_B = YSD_V005_TOLERAN-TOLERANCIA_B .
    IF SY-SUBRC = 0.
    DELETE YSD_T005_TOLERAN .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM YSD_T005_TOLERAN WHERE
  VKORG = YSD_V005_TOLERAN-VKORG AND
  KSCHL = YSD_V005_TOLERAN-KSCHL AND
  TOLERANCIA_A = YSD_V005_TOLERAN-TOLERANCIA_A AND
  TOLERANCIA_B = YSD_V005_TOLERAN-TOLERANCIA_B .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR YSD_T005_TOLERAN.
    ENDIF.
YSD_T005_TOLERAN-MANDT =
YSD_V005_TOLERAN-MANDT .
YSD_T005_TOLERAN-VKORG =
YSD_V005_TOLERAN-VKORG .
YSD_T005_TOLERAN-KSCHL =
YSD_V005_TOLERAN-KSCHL .
YSD_T005_TOLERAN-TOLERANCIA_A =
YSD_V005_TOLERAN-TOLERANCIA_A .
YSD_T005_TOLERAN-TOLERANCIA_B =
YSD_V005_TOLERAN-TOLERANCIA_B .
YSD_T005_TOLERAN-UNAME =
YSD_V005_TOLERAN-UNAME .
YSD_T005_TOLERAN-AEDTM =
YSD_V005_TOLERAN-AEDTM .
YSD_T005_TOLERAN-UZEIT =
YSD_V005_TOLERAN-UZEIT .
    IF SY-SUBRC = 0.
    UPDATE YSD_T005_TOLERAN ##WARN_OK.
    ELSE.
    INSERT YSD_T005_TOLERAN .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_YSD_V005_TOLERAN-UPD_FLAG,
STATUS_YSD_V005_TOLERAN-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_YSD_V005_TOLERAN.
  SELECT SINGLE * FROM YSD_T005_TOLERAN WHERE
VKORG = YSD_V005_TOLERAN-VKORG AND
KSCHL = YSD_V005_TOLERAN-KSCHL AND
TOLERANCIA_A = YSD_V005_TOLERAN-TOLERANCIA_A AND
TOLERANCIA_B = YSD_V005_TOLERAN-TOLERANCIA_B .
YSD_V005_TOLERAN-MANDT =
YSD_T005_TOLERAN-MANDT .
YSD_V005_TOLERAN-VKORG =
YSD_T005_TOLERAN-VKORG .
YSD_V005_TOLERAN-KSCHL =
YSD_T005_TOLERAN-KSCHL .
YSD_V005_TOLERAN-TOLERANCIA_A =
YSD_T005_TOLERAN-TOLERANCIA_A .
YSD_V005_TOLERAN-TOLERANCIA_B =
YSD_T005_TOLERAN-TOLERANCIA_B .
YSD_V005_TOLERAN-UNAME =
YSD_T005_TOLERAN-UNAME .
YSD_V005_TOLERAN-AEDTM =
YSD_T005_TOLERAN-AEDTM .
YSD_V005_TOLERAN-UZEIT =
YSD_T005_TOLERAN-UZEIT .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_YSD_V005_TOLERAN USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE YSD_V005_TOLERAN-VKORG TO
YSD_T005_TOLERAN-VKORG .
MOVE YSD_V005_TOLERAN-KSCHL TO
YSD_T005_TOLERAN-KSCHL .
MOVE YSD_V005_TOLERAN-TOLERANCIA_A TO
YSD_T005_TOLERAN-TOLERANCIA_A .
MOVE YSD_V005_TOLERAN-TOLERANCIA_B TO
YSD_T005_TOLERAN-TOLERANCIA_B .
MOVE YSD_V005_TOLERAN-MANDT TO
YSD_T005_TOLERAN-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'YSD_T005_TOLERAN'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN YSD_T005_TOLERAN TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'YSD_T005_TOLERAN'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
