PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_YSD_V004_VALMACE CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD YSD_V004_VALMACE-VKORG .
    FIELD YSD_V004_VALMACE-WERKS .
    FIELD YSD_V004_VALMACE-SELECTION .
    FIELD YSD_V004_VALMACE-UNAME .
    FIELD YSD_V004_VALMACE-AEDTM .
    FIELD YSD_V004_VALMACE-UZEIT .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD YSD_V004_VALMACE-VKORG .
    FIELD YSD_V004_VALMACE-WERKS .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
